version: '3.8'
services:
    app:
        build: 
            context: ./
            dockerfile: Dockerfile
        env_file: .env
        restart: always
        networks:
            - back_net
        volumes:
            - ./src/:/app/src
        ports:
           - "5000:5000"
        depends_on:
            - cache
    cache:
        image: redis:alpine
        command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
        restart: always
        env_file: .env
        networks:
            - back_net
#        ports:
#            - "6379:6379"
    storage:
        networks:
            - back_net
        extends:
            file: ../storage/docker-compose.yml
            service: database
        volumes:
            - ../storage/db/postgresql:/var/lib/postgresql
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=warlords
networks:
    back_net:
        external: false
