FROM node:18

WORKDIR /app
COPY package.json /app/
COPY nodemon.json /app/
COPY index.js /app/
# COPY .env /app/

ENV GAME_MACHINE_PORT 5000

RUN echo 'GAME_MACHINE_PORT=${GAME_MACHINE_PORT}' >> .env

ENV POSTGRES_HOST storage
ENV POSTGRES_USER root
ENV POSTGRES_PASSWORD 123456
ENV POSTGRES_DB warlords

RUN echo 'POSTGRES_HOST=${POSTGRES_HOST}' >> .env
RUN echo 'POSTGRES_USER=${POSTGRES_USER}' >> .env
RUN echo 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}' >> .env
RUN echo 'POSTGRES_DB=${POSTGRES_DB}}' >> .env

ENV MEMCACHE_SERVERS cache:11211
ENV MEMCACHED_USERNAME root
ENV MEMCACHED_PASSWORD 123456
ENV MEMCACHED_CONN_LIMIT 1024
ENV MEMCACHED_MAX_CONNECTIONS 2000
ENV MEMCACHED_MEMORY_LIMIT 1024
ENV MEMCACHED_THREADS 8

RUN echo 'MEMCACHE_SERVERS=${MEMCACHE_SERVERS}' >> .env
RUN echo 'MEMCACHED_USERNAME=${MEMCACHED_USERNAME}' >> .env
RUN echo 'MEMCACHED_PASSWORD=${MEMCACHED_PASSWORD}' >> .env
RUN echo 'MEMCACHED_CONN_LIMIT=${MEMCACHED_CONN_LIMIT}' >> .env
RUN echo 'MEMCACHED_MAX_CONNECTIONS=${MEMCACHED_MAX_CONNECTIONS}' >> .env
RUN echo 'MEMCACHED_MEMORY_LIMIT=${MEMCACHED_MEMORY_LIMIT}' >> .env
RUN echo 'MEMCACHED_THREADS=${MEMCACHED_THREADS}' >> .env

ENV REDIS_HOST cache
ENV REDIS_PORT 6379
ENV REDIS_PASSWORD 12345

RUN echo 'REDIS_HOST=${REDIS_HOST}' >> .env
RUN echo 'REDIS_PORT=${REDIS_PORT}' >> .env
RUN echo 'REDIS_PASSWORD=${REDIS_PASSWORD}' >> .env

RUN npm install -g nodemon@2.0.22 && npm install

EXPOSE ${GAME_MACHINE_PORT}

VOLUME /app/src

CMD ["nodemon"]